baseURL = 'https://tty503.com/'
languageCode = 'es-ve'
title = 'tty503'
theme = "hugo-theme-nix"

[sitemap]
  changeFreq = 'hourly'

[params]
  Name = "Christian Marquez"
  HeaderUsername = "tty503"
  HeaderHostname = "website"
  About = "A passionate software developmentğŸ§‘â€ğŸ’» and computer securityğŸ´â€â˜ ï¸."
  ProfilePicture = "avatar.jpg"
  goToTop = true
  
  GithubID = "tty503"
  LinkedInID = "tty503"
  TelegramID = "tty503"
  TwitterID = "tty_503"

[params.whoami]
  name = "whoami"
  url = "/whoami"  

[params.Favicon]
  name = "icon"
  url = "/favicon.ico"  


[[menu.header]]
  identifier = "post"   
  name = "posts"        
  url = "/posts"
  weight = 1

[[menu.header]]
  parent = "post"       
  name = "All Posts"
  url = "/posts"
  weight = 1

[[menu.header]]
  parent = "post"
  name = "Categories"
  url = "/categories"
  weight = 2

[[menu.header]]
  parent = "post"
  name = "Tags"
  url = "/tags"
  weight = 3

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
