baseURL = 'https://tty503.com/'
languageCode = 'es-ve'
title = 'tty503'
theme = "hugo-blog-awesome"

[params.author]
  avatar = "avatar.jpg" 
  name = "Christian Marquez"
  description = "A passionate software developmentğŸ§‘â€ğŸ’» and computer securityğŸ´â€â˜ ï¸."

[sitemap]
  changeFreq = 'hourly'

[params]
  goToTop = true

[[params.socialIcons]]
name = "linkedin"
url = "https://linkedin.com/in/tty503"

[[params.socialIcons]]
name = "github"
url = "https://github.com/tty503"

[[params.socialIcons]]
name = "twitter"
url = "https://x.com/tty_503"

[[params.socialIcons]]
name = "Telegram"
url = "https://t.me/tty503"


[menu]
[[menu.main]]
    pageRef="/"
    name = 'Inicio'
    url = '/'
    weight = 10
[[menu.main]]
    pageRef="posts"
    name = 'Blog'
    url = '/posts/'
    weight = 20
[[menu.main]]
    pageRef="about"
    name = 'Sobre Mi'
    url = '/about/'
    weight = 30


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
